### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by danielgindi**
Hi!

I've made it a bit easier to configure.

1. If you have multiple calendars on your screen, you can style each separately
2. Most style settings are now propagating if you set the `style` property even after layout
3. Lazy loading of month info, so a million years range could be setup without any performance impact
4. Better sync of `displayDate`
5. You could now control placement of header components, or deliberately cause month label to be 0.0 height to hide it.
6. RTL support
7. Support for showing adjacent days

### CODE REVIEW

**Comment by mmick66** [comment]
Wow! You seem to have done quite a bit of work! Thank you... really appreciated.

**Comment by mmick66** [comment]
Could I ask for a huge favour? If you could also update the README to reflect your changes. Just a basic example of how to use your new code, no worries about the writing style, I will edit that later. Thanks again...

**Comment by danielgindi** [comment]
Everything should work the same, so all changes for the user is in `Style`, and in `forceLtr` property.
So users wanting a global styling will modify `CalendarView.Style.Default` instead of `CalendarView.Style`. For view-specific style, instantiate a `Style` and assign to `calendarView.style`.
For showing adjacent days, they will modify the `Style` for that.
If a user wants to handle selection of adjacent days, they could use the delegates.

An example for auto scrolling to adjacent days without selection:
```
    func calendar(_ calendar: CalendarView, canSelectDate date: Date) -> Bool
    {
        let selectedMonth = calendar.calendar.component(.month, from: date)
        let displayMonth = calendar.displayDate == nil ? 0 : calendar.calendar.component(.month, from: calendar.displayDate!)
        
        if selectedMonth != displayMonth
        {
            calendar.setDisplayDate(date, animated: true)
            return false
        }
        
        return true
    }
```

**Comment by danielgindi** [comment]
Everything else is under the hood :-)

**Pull request merged**
