### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by RemyDCF**
This pull request add Carthage support to the project

### CODE REVIEW

**Comment by mmick66** [comment]
I do not use Carthage so I can't comment. Are you sure you know what you are doing? If so, I will add it to the main branch.

**Comment by RemyDCF** [comment]
It's working for me.
My pull request added a shared framework scheme, as described in the [README.md of Carthage](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)

**Comment by mmick66** [comment]
Thanks!

**Comment by mmick66** [comment]
Could you please add a single line describing how to install it through Carthage on the project's README? Just over the "manual" installation?

**Comment by RemyDCF** [comment]
Ok, I will open a new pull request

**Pull request merged**
